add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """$character"""

right_format = """$directory$cmd_duration"""

palette = "dark-orchid"

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = ""
error_symbol = ""

[directory]
format = "[$path]($style)"
style = "zinc_500"
truncation_length = 2
read_only = " ◈"
use_os_path_sep = true

[cmd_duration]
format = " [took $duration]($style)"
style = "zinc_500"

[palettes.dark-orchid]
zinc_300 = "#d4d4d8"
zinc_700 = "#3f3f46"
zinc_500 = "#71717a"
