'$schema' = 'https://starship.rs/config-schema.json'

palette = 'custom'

add_newline = true

format = """
$os \
$directory\
$git_branch\
$git_status\
$character\
"""

[os]
format = '[$symbol ](fg:purple)'
disabled = false

[os.symbols]
Arch = ''

[directory]
format = '[$path](fg:purple) '
truncate_to_repo = true
truncation_length = 6
read_only = ''
read_only_style = ''

[git_branch]
format = '([\($branch\)](fg:purple) )'

[git_status]
format = '([\[$all_status\]](fg:purple) )'

[character]
format = '[~>](fg:purple) '

[palettes.custom]
purple = '#7300ff'
white = '#ffffff'
