theme = "dark_orchid"

[editor]
mouse = false
middle-click-paste = false
shell = [ "/usr/bin/fish" ]
line-number = "relative"
#cursorline = true
color-modes = true
auto-completion = true
path-completion = true
auto-format = false
preview-completion-insert = false
completion-trigger-len = 1
undercurl = true
bufferline = "multiple"
insert-final-newline = true
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = "all"
clipboard-provider = "wayland"
default-yank-register = "+"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.smart-tab]
enable = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "separator", "spinner", "separator", "diagnostics"]
center = ["file-name"]
right = ["position", "separator", "selections", "separator", "file-line-ending", "separator", "file-type", "separator", "version-control"]
separator = "  "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.lsp]
enable = true
auto-signature-help = true
display-messages = false
