[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.check]
command = "check"

[language-server.rust-analyzer.config]
procMacro.enable = true
checkOnSave = false
diagnostics.experimental.enable = false
cargo.features = "all"
cargo.buildScripts.enable = false

[[language]]
name = "rust"
file-types = ["rs"]
language-servers = ["rust-analyzer"]
roots = ["Cargo.toml", "Cargo.lock"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.typescript-language-server.config]
hostInfo = "helix"

[language-server.typescript-language-server.config.preferences]
quotePreference = "double"
jsxAttributeCompletionStyle = "none"

#[language-server.angular-ls]
#command = "ngserver"
#args = [
#  "--ngProbeLocations",
#  "${$NODE_MODULES_GLOBAL}",
#  "--tsProbeLocations",
#  "${$NODE_MODULES_GLOBAL}",
#  "--stdio",
#  # If this for some reason doesn't work, try replacing ${NODE_MODULES_GLOBAL} with the absolute paths, e.g. output of `npm root -g`
#]

#[language-server.tsgo]
#command = "tsgo"
#args = [
#  "--lsp",
#  "--stdio"
#]

#[language-server.tsgo.config.typescript]
#updateImportsOnFileMove.enabled = "always"
#suggest.completeFunctionCalls = true
#tsserver.enableTracing = true
#inlayHints.parameterNames.enabled = "all"
#inlayHints.parameterTypes.enabled = false
#inlayHints.variableTypes.enabled = false
#inlayHints.propertyDeclarationTypes.enabled = false
#inlayHints.functionLikeReturnTypes = false
#inlayHints.enumMemberValues.enabled = false
#format.enable = false
#format.semicolons = "remove"
#preferences.importModuleSpecifier = "non-relative"
#preferences.importModuleSpecifierEnding = "auto"
#tsserver.experimental.enableProjectDiagnostics = true

[[language]]
name = "typescript"
file-types = ["ts", "mts", "cts", "js", "mjs", "cjs"]
formatter = { command = "oxfmt" }
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
file-types = ["tsx", "jsx", "mtsx", "ctsx", "mjsx", "cjsx"]
formatter = { command = "oxfmt" }
language-servers = ["typescript-language-server"]

[language-server.css]
command = "vscode-css-language-server"
args = ["--stdio"]

[[language]]
name = "css"
file-types = ["css", "scss", "less", "sass"]
formatter = { command = "oxfmt" }
language-servers = ["css"]

[language-server.html]
command = "vscode-html-language-server"
args = ["--stdio"]

[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.tailwindcss.settings.tailwindCSS]
classFunctions = ["cva", "cx"]

[[language]]
name = "html"
file-types = ["html", "htm"]
formatter = { command = "oxfmt" }
language-servers = ["html", "tailwindcss", "angular-ls"]

[language-server.json]
command = "vscode-json-language-server"
args = ["--stdio"]

[[language]]
name = "json"
file-types = ["json", "jsonc", "json5"]
formatter = { command = "oxfmt" }
language-servers = ["json"]

[[language]]
name = "scss"
file-types = ["scss", "sass"]
formatter = { command = "oxfmt" }

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
formatter = { command = "oxfmt" }

[[language]]
name = "markdown"
file-types = ["md", "mdx"]
formatter = { command = "oxfmt" }

[[language]]
name = "toml"
file-types = ["toml"]
formatter = { command = "oxfmt" }
