classic: false

blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

color:
  theme: custom

icons:
  when: always
  theme: fancy
  separator: "  "

sorting:
  dir-grouping: first
  column: name

layout: grid

size: bytes

header: true

indicators: true

total-size: true
