classic: false

blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

color:
  when: never

icons:
  when: always
  theme: fancy
  separator: " "

sorting:
  dir-grouping: first
  column: name

layout: grid

size: default

header: true

indicators: true

total-size: true
