[privat@kovtyk.com]
copy-to = Sent
default = INBOX
username = privat@kovtyk.com
from = Simon Kovtyk <privat@kovtyk.com>
source = imaps://privat%40kovtyk.com@mail.simonkov.dev:993
source-cred-cmd = /home/simonkov/.bin/aerc-secret-lookup privat@kovtyk.com
outgoing = smtps://privat%40kovtyk.com@mail.simonkov.dev:465
outgoing-cred-cmd = /home/simonkov/.bin/aerc-secret-lookup privat@kovtyk.com

[simon@kovtyk.com]
copy-to = Sent
default = INBOX
username = simon@kovtyk.com
from = Simon Kovtyk <simon@kovtyk.com>
source = imaps://simon%40kovtyk.com@mail.simonkov.dev:993
source-cred-cmd = /home/simonkov/.bin/aerc-secret-lookup simon@kovtyk.com
outgoing = smtps://simon%40kovtyk.com@mail.simonkov.dev:465
outgoing-cred-cmd = /home/simonkov/.bin/aerc-secret-lookup simon@kovtyk.com

[simon@kovtyk-connect.com]
copy-to = Sent
default = INBOX
username = simon@kovtyk-connect.com
from = Simon Kovtyk <simon@kovtyk-connect.com>
source = imaps://simon%40kovtyk-connect.com@mail.simonkov.dev:993
source-cred-cmd = /home/simonkov/.bin/aerc-secret-lookup simon@kovtyk-connect.com
outgoing = smtps://simon%40kovtyk-connect.com@mail.simonkov.dev:465
outgoing-cred-cmd = /home/simonkov/.bin/aerc-secret-lookup simon@kovtyk-connect.com

[master@simonkov.dev]
copy-to = Sent
default = INBOX
username = master@simonkov.dev
from = Simon Kovtyk <master@simonkov.dev>
source = imaps://master%40simonkov.dev@mail.simonkov.dev:993
source-cred-cmd = /home/simonkov/.bin/aerc-secret-lookup master@simonkov.dev
outgoing = smtps://master%40simonkov.dev@mail.simonkov.dev:465
outgoing-cred-cmd = /home/simonkov/.bin/aerc-secret-lookup master@simonkov.dev

[dev@orgvr.org]
copy-to = Sent
default = INBOX
username = dev@orgvr.org
from = IOV DEV <dev@orgvr.org>
source = imaps://dev%40orgvr.org@mail.orgvr.org:993
source-cred-cmd = /home/simonkov/.bin/aerc-secret-lookup dev@orgvr.org
outgoing = smtps://dev%40orgvr.org@mail.orgvr.org:465
outgoing-cred-cmd = /home/simonkov/.bin/aerc-secret-lookup dev@orgvr.org
