--[[
--
-- Set mode, that hyprland will use.
--
-- Possible modes are: "dark-orchid", "dark-orchid-demo"
--
]]--
local mode = "dark-orchid"

hl.monitor({
  output = "DP-2",
  mode = "2560x1440@160",
  position = "0x0",
  scale = "auto"
})
hl.monitor({
  output = "DP-1",
  mode = "2560x1440@144",
  position = "-2560x0",
  scale = "auto"
})
hl.monitor({
  output = "DP-3",
  mode = "1920x1080@60",
  position = "2560x0",
  scale = "auto"
})
hl.monitor({
  output = "HDMI-A-1",
  mode = "1920x1080@60",
  position = "0x-1080",
  scale = "auto"
})

hl.on("hyprland.start", function ()
  hl.exec_cmd("dbus-update-activation-environment --all")
  hl.exec_cmd("hyprlock")
  hl.exec_cmd("hyprpm reload")
  hl.exec_cmd("udiskie")
  hl.exec_cmd("hypridle")

  if mode == "dark-orchid" then
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper --config /home/simonkov/.config/hypr/hyprpaper/dark-orchid.conf")
  elseif mode == "dark-orchid-demo" then
    hl.exec_cmd("hyprpaper --config /home/simonkov/.config/hypr/hyprpaper/dark-orchid-demo.conf")
  end
end)

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("NVD_BACKEND", "direct")
hl.env("__GL_THREADED_OPTIMIZATION", 1)
hl.env("__GL_SHADER_DISK_CACHE", 1)
hl.env("__GL_SHADER_DISK_CACHE_PATH", "/var/cache/nvidia-shader")
hl.env("GTK_THEME", "Adwaita-dark")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

if mode == "dark-orchid" then
  hl.config({
    general = {
      gaps_out = 16,
      border_size = 1
    }
  })
elseif mode == "dark-orchid-demo" then
  hl.config({
    general = {
      gaps_out = 192,
      border_size = 0
    }
  })
end

hl.config({
  autogenerated = false,
  general = {
    gaps_in  = 8,
    col = {
      active_border = {
        colors = {
          "rgb(3f3f46)"
        },
        angle = 90
      },
      inactive_border = 0x00000000,
    },
    resize_on_border = false,
    allow_tearing = false,
    layout = "dwindle"
  },
  decoration = {
    rounding = 16,
    rounding_power = 2,
    active_opacity = 1.0,
    inactive_opacity = 1.0,
    shadow = {
      enabled = true,
      range = 4,
      render_power = 3,
      color = 0xee1a1a1a
    },
    blur = {
      enabled = true,
      size = 2,
      passes = 3,
      vibrancy = 0.1696
    },
  },
  animations = {
    enabled = true
  },
  dwindle = {
    preserve_split = true
  },
  misc = {
    force_default_wallpaper = false,
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
    middle_click_paste = false
  },
  cursor = {
    no_hardware_cursors = false,
    default_monitor = "DP-2"
  },
  input = {
    kb_layout = "de",
    kb_variant = "",
    kb_model = "",
    kb_options = "",
    kb_rules = "",
    accel_profile = "flat",
    follow_mouse = 1,
    sensitivity = 0
  }
})

if hl.plugin.dynamic_cursors ~= nil then
  hl.config({
    plugin = {
      dynamic_cursors = {
        enabled = true,
        mode = "stretch",
        stretch = {
          limit = 3000,
          window = 200
        },
        shake = {
          enabled = false,
          ipc = false
        }
      }
    }
  })
end

if hl.plugin.hyprfocus ~= nil then
  hl.config({
    hyprfocus = {
      mode = "flash",
      fade_opacity = 0.6
    }
  })
end

hl.workspace_rule({
  workspace = 1,
  monitor = "DP-2",
  default = true,
  persistent = true
})
hl.workspace_rule({
  workspace = 2,
  monitor = "DP-2",
  persistent = true
})
hl.workspace_rule({
  workspace = 3,
  monitor = "DP-2",
  persistent = true
})
hl.workspace_rule({
  workspace = 4,
  monitor = "DP-2",
  persistent = true
})

hl.window_rule({
  name  = "suppress-maximize-events",
  match = { class = ".*" },
  suppress_event = "maximize"
})
hl.window_rule({
  name = "fix-xwayland-drags",
  no_focus = true,
  match = {
    class = "^$",
    title = "^$",
    xwayland = true,
    float = true,
    fullscreen = false,
    pin = false
  }
})
hl.window_rule({
  name = "Hide KeepassXC from Screen Sharing",
  no_screen_share = true,
  match = {
    class = "org.keepassxc.KeePassXC"
  }
})
hl.window_rule({
  name = "Hide Firefox Private Browsing from Screen Sharing",
  no_screen_share = true,
  match = {
    class = "firefox",
    title = ".*Mozilla Firefox Private Browsing$"
  }
})

hl.curve("easeOutQuint", {
  type = "bezier",
  points = { { 0.22, 1 }, { 0.36, 1 } }
})
hl.animation({
  leaf = "global",
  enabled = true,
  speed = 3,
  bezier = "easeOutQuint"
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 3,
  bezier = "easeOutQuint",
  style = "slidefadevert"
})

local mainMod = "SUPER"

local terminal = "kitty"
local fileManager = terminal .. " -e yazi"
local browser = "thorium-browser"
local menu = "rofi -show drun"
local email = terminal .. " -e aerc"
local soundMixer = terminal .. " -e wiremix"
local music = terminal .. " -e spotify_player"

hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(soundMixer))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(music))
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd(email))

hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("swaync-client -t"))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. "+ CTRL + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. "+ CTRL + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. "+ CTRL + up", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. "+ CTRL + down", hl.dsp.window.move({ direction = "down" }))

hl.bind(mainMod .. "+ SHIFT + left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
hl.bind(mainMod .. "+ SHIFT + right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
hl.bind(mainMod .. "+ SHIFT + up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
hl.bind(mainMod .. "+ SHIFT + down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

for i = 1, 4 do
  local key = i % 10

  hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i}))
  hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })
