[general]
live_config_reload = true

[env]
TERMINAL_EMULATION = "true"

[window]
padding = { x = 8, y = 8 }
decorations = "Buttonless"
opacity = 0.8
blur = false

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = { shape = "Block", blinking = "Never" }
unfocused_hollow = false

[mouse]
hide_when_typing = true

[colors.primary]
background = "#000000"
foreground = "#ffffff"
