require("mappings")
require("settings")
require("filetypes")
require("pack")

require("plugins.dark_orchid")
require("plugins.neotree")
require("plugins.icons")
require("plugins.image")
require("plugins.lualine")
require("plugins.barbar")
require("plugins.lspconfig")
require("plugins.indentmini")
require("plugins.pairs")
require("plugins.gitsigns")
require("plugins.dashboard")
